name: build & deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.2.2'
      
      - name: Install dependencies
        run: poetry install

      # - name: Version
      #   run: echo "VERSION=$(poetry version --short)" >> $GITHUB_ENV
      #   id: version
      
      - name: Publish
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}" && poetry publish --build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: "Find it on PyPI: [https://pypi.org/project/pdf-scout/](https://pypi.org/project/pdf-scout/)"